"use client"
import NavAside from '@/components/NavAside/NavAside'
import './globals.css'
import { Inter } from 'next/font/google'
import Logo from '@/components/Logo/Logo'
import ClientOption from '@/components/ClientOption/ClientOption'
import { ParallaxProvider } from 'react-scroll-parallax';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ParallaxProvider>
        <div className='main-app'>
          {/* <div className='popup'>
            <form>
              <input type='text'></input>
              <input type='password'></input>
            </form>
          </div> */}
          <div className='main-app-whitespace menu'>
            <Logo/>
            <NavAside/>
          </div>
          {children}
          <div className='main-app-whitespace index'>
            <ClientOption/>
            <div><p><span>SCROLL</span><span>DOWN</span></p></div>
            <div></div>
            <div></div>
          </div>
        </div>
        </ParallaxProvider>
      </body>
    </html>
  )
}


/*<p><span>SCROLL</span><span>DOWN</span></p>*/