import './globals.css'
import { Inter } from 'next/font/google'

import WrapperClient from '@/components/Wrapper/Client/main'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const protectedSegment : { [key: string]: boolean } = {
    __PAGE__: false,
    dashboard: true,
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode,
}) {

  const segment : string = (children as any)?.props?.childProp.segment;

  return (
    <html lang="en">
        <body className={inter.className}>
          {
            segment === '__PAGE__' ?
            <WrapperClient>{children}</WrapperClient> :
            <>{children}</>
          }
        </body>
    </html>
  )
}